Models/ApplicationType.cs
using System.ComponentModel.DataAnnotations;

namespace FCCNet5.Models
{
    public class ApplicationType
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FCCNet5.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        
        [Required]
        public string Name { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Display Order must be greater than zero")]
        [DisplayName("Display Order")]
        public int DisplayOrder { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace FCCNet5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ApplicationTypeController.cs
using System.Collections.Generic;
using FCCNet5.Data;
using FCCNet5.Models;
using Microsoft.AspNetCore.Mvc;

namespace FCCNet5.Controllers
{
    public class ApplicationTypeController : BaseControllerClass
    {
        public ApplicationTypeController(ApplicationDbContext db) : base(db)
        {}

        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objList = _db.ApplicationTypes;
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(ApplicationType obj)
        {
            if (ModelState.IsValid) 
            {
                _db.ApplicationTypes.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Create", obj);
        }

        public IActionResult Edit(int? id)
        {
            var obj = _db.ApplicationTypes.Find(id);
            if(obj==null) return NotFound();

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType obj)
        {
            if(ModelState.IsValid) {
                _db.ApplicationTypes.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _db.ApplicationTypes.Find(id);
            if(obj==null) return NotFound();

            _db.ApplicationTypes.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/CategoryController.cs
using System.Collections.Generic;
using FCCNet5.Data;
using FCCNet5.Models;
using Microsoft.AspNetCore.Mvc;

namespace FCCNet5.Controllers
{
    public class CategoryController : BaseControllerClass
    {
        public CategoryController(ApplicationDbContext db) : base(db)
        {}

        public IActionResult Index()
        {
            IEnumerable<Category> objList = _db.Categories;
            
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Create", obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Categories.Find(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _db.Categories.Find(id);
            if (obj == null) return NotFound();

            _db.Categories.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FCCNet5.Models;

namespace FCCNet5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/ApplicationType/Create.cshtml
@model FCCNet5.Models.ApplicationType

@{
    ViewData["Title"] = "Create Application Type";
}

<h1 class="text-primary mb-5">@ViewData["Title"]</h1>

<form method="post" asp-action="Store">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <input type="submit" value="Save" class="btn btn-primary">
    <a asp-action="Index" class="btn btn-secondary">Back</a>
</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial"></partial> }
}

Views/ApplicationType/Edit.cshtml
@model FCCNet5.Models.ApplicationType

@{
    ViewData["Title"] = "Edit Application Type";
}

<h1 class="text-primary mb-5">@ViewData["Title"]</h1>

<form method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button class="btn btn-primary"><span class="mdi mdi-content-save"></span> Update</button>
    <a asp-action="Index" class="btn btn-secondary"><i class="mdi mdi-arrow-left"></i> Back</a>
</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial"></partial> }
}

Views/ApplicationType/Index.cshtml
@model IEnumerable<FCCNet5.Models.ApplicationType>

@{
    ViewData["Title"] = "Application Types";
}

<div class="row mb-5">
    <div class="col-6">
        <h1 class="text-primary">@ViewData["Title"]</h1>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-primary" asp-action="Create">Create Application Type</a>
    </div>
</div>

@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Application Type Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.Name</td>
                    <td class="d-flex justify-content-end">
                        <a asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-info mr-2"><span class="mdi mdi-pencil"></span></a>
                        <form asp-action="Delete" method="post">
                            <input hidden name="Id" value="@obj.Id">
                            <button class="btn btn-danger"><span class="mdi mdi-delete"></span></button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No Application Types to show</p>
}

Views/Category/Create.cshtml
@model FCCNet5.Models.Category

@{
    ViewData["Title"] = "Create Category";
}

<h1 class="text-primary mb-5">Create Category</h1>

<form method="post" asp-action="Store">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DisplayOrder"></label>
        <input asp-for="DisplayOrder" class="form-control">
        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
    </div>

    <input type="submit" value="Save" class="btn btn-primary">
    <a asp-action="Index" class="btn btn-secondary">Back</a>
</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial"></partial> }
}

Views/Category/Edit.cshtml
@model FCCNet5.Models.Category

@{
    ViewData["Title"] = "Edit Category";
}

<h1 class="text-primary mb-5">@ViewData["Title"]</h1>

<form method="post">
    <input asp-for="Id" hidden >
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DisplayOrder"></label>
        <input asp-for="DisplayOrder" class="form-control">
        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
    </div>

    <input type="submit" value="Update" class="btn btn-primary">
    <a asp-action="Index" class="btn btn-secondary">Back</a>
</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial"></partial> }
}

Views/Category/Index.cshtml
@model IEnumerable<FCCNet5.Models.Category>

@{
    ViewData["Title"] = "Category";
}

<div class="row mb-5">
    <div class="col-6">
        <h1 class="text-primary">Categories</h1>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-primary" asp-action="Create">Create New Category</a>
    </div>
</div>

@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Display Order</th>
                <th>Category Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.DisplayOrder</td>
                    <td>@obj.Name</td>
                    <td class="w-25 text-right">
                            <div class="d-flex justify-content-end">
                                <a asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-info mr-2"><span class="mdi mdi-pencil"></span></a>
                                <form asp-action="Delete" method="post">
                                    <input value="@obj.Id" name="Id" hidden>
                                    <button class="btn btn-danger"><span class="mdi mdi-delete"></span></button>
                                </form>
                            </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No Categories to show</p>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FCCNet5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@mdi/font@5.9.55/css/materialdesignicons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FCCNet5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Types</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FCCNet5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>